controller_names:
  - j2s7s300_arm_controller

j2s7s300_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - j2s7s300_joint_1
    - j2s7s300_joint_2
    - j2s7s300_joint_3
    - j2s7s300_joint_4
    - j2s7s300_joint_5
    - j2s7s300_joint_6
    - j2s7s300_joint_7
