j2s7s300_arm_controller:
  ros__parameters:
    joints:
      - j2s7s300_joint_1
      - j2s7s300_joint_2
      - j2s7s300_joint_3
      - j2s7s300_joint_4
      - j2s7s300_joint_5
      - j2s7s300_joint_6
      - j2s7s300_joint_7
    write_op_modes:
      - j2s7s300_joint_1
      - j2s7s300_joint_2
      - j2s7s300_joint_3
      - j2s7s300_joint_4
      - j2s7s300_joint_5
      - j2s7s300_joint_6
      - j2s7s300_joint_7
