joint_limits:
  j2s7s300_joint_1:
    has_velocity_limits: true
    max_velocity: 0.984
    has_acceleration_limits: true
    max_acceleration: 2.952
  j2s7s300_joint_2:
    has_velocity_limits: true
    max_velocity: 0.984
    has_acceleration_limits: true
    max_acceleration: 2.952
  j2s7s300_joint_3:
    has_velocity_limits: true
    max_velocity: 0.984
    has_acceleration_limits: true
    max_acceleration: 2.952
  j2s7s300_joint_4:
    has_velocity_limits: true
    max_velocity: 0.984
    has_acceleration_limits: true
    max_acceleration: 2.952
  j2s7s300_joint_5:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: true
    max_acceleration: 4.713
  j2s7s300_joint_6:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: true
    max_acceleration: 4.713
  j2s7s300_joint_7:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: true
    max_acceleration: 4.713
  j2s7s300_joint_finger_1:
    has_velocity_limits: true
    max_velocity: 3.1415927
    has_acceleration_limits: true
    max_acceleration: 314.15927
  j2s7s300_joint_finger_2:
    has_velocity_limits: true
    max_velocity: 3.1415927
    has_acceleration_limits: true
    max_acceleration: 314.15927
  j2s7s300_joint_finger_3:
    has_velocity_limits: true
    max_velocity: 3.1415927
    has_acceleration_limits: true
    max_acceleration: 314.15927
